### ISSUE TITLE
Excessive permissions

### ISSUE THREAD

**Issue by pirj** [gitrun/poll#99]
Why does it ask for private repo access on log in? Deploy keys, wiki, settings, webhooks, code?
This should be narrowed down to public repos and issues.
Those who will want to use gitpoll for private repos will be hosting on their own and will be able to tune that.

**Comment by podviaznikov** [comment]
Thanks for the posting this issue @pirj. I changed oauth scope from `repo` to `public_repo`.
I do agree with your comment that for private issues people can self-host git poll app.

The problem with write access is that GitHub doesn't have granular scopes.
GitPoll needs ability to write comment on github issue. For that it unfortunately needs `repo` scope which is write access.

I hope GitHub will improve their scopes in future. You can check docs here now: https://developer.github.com/v3/oauth/.

**Comment by pirj** [comment]
Thanks a lot!

**Comment by L2G** [comment]
It still doesn't make sense to me that GitPoll would need such wide-open permissions just to post comments to issues. Can't all GitHub users post comments on an issue or even create new issues on any public repo without special permissions for each repo?
